#################################
#
# publish config
#
#
#
#################################
# Local repo or NOT
localRepo=false
#################################
# Maven info
groupId=com.tencent.kuiklybase
artifactId=bridge
#################################
# Pom file info
name=kuiklyx-bridge
description="Kuikly plugin router base bridge module."
url=
#################################

# account info
username=g_kuikly_open
token=0680d5a288ae11f0946a5254002e0cf4
# repo url
repoUrl=https://mirrors.tencent.com/repository/maven/kuikly-open/
#################################