#################################
#
# publish config
#
#
#
#################################
# account info
username=
token=
# repo release url
sourceUrl=
# repo snapshot url
sourceUrlSnapshot=
# repo base dir, sub_path=version
sourcePath=iOS/cocoapods/release
sourceDebugPath=iOS/cocoapods/debug

### CNB ###
# account info
cnb_username=
cnb_token=
# repo release url
cnb_sourceUrl=
# repo snapshot url
cnb_sourceUrlSnapshot=
# repo base dir, sub_path=version
cnb_sourcePath=ios/cocoapods/release
cnb_sourceDebugPath=ios/cocoapods/debug
#################################
