#################################
#
# publish config
#
#
#
#################################
# Local repo or NOT
localRepo=false
#################################
# Maven info
groupId=com.tencent.kuiklybase
artifactId=bridge
#################################
# Pom file info
name=kuiklyx-bridge
description="Kuikly plugin router base bridge module."
url=
#################################
email=
# account info
username=xxx
token=xxx
# repo url
repoUrl=xxx
repoUrlSnapshot=
#################################